CREATE TABLE IF NOT EXISTS Country (id VARCHAR(250) PRIMARY KEY, name VARCHAR(250) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS Employee (id INT AUTO_INCREMENT PRIMARY KEY, firstName VARCHAR(250) NOT NULL, secondName VARCHAR(250) NOT NULL, birthPlace VARCHAR(250) NOT NULL);
